### ISSUE TITLE
How to Create Censored regression

### ISSUE THREAD

**Issue by snakecy** [wush978/KDD2015wpp#1]
Thanks for your project.
there are some questions as following,
(1) why to set new bidding price as 0.5*biddingprice?
(2) why just use win data to split to is_win true or false?
(3) how to initial the win rate, and set each as 0.5? and the win rate seems to just have win data?
(4) how to get the win rate ?
(5) for winning price estimation, in linear training, wp ~ features + bidprice is right?  how to use censored regression?

**Comment by wush978** [comment]
Dear @luckyandy ,

We have published a paper and you can find the answer in our paper.

Here is the link of my slide to introduce our paper in KDD 2015: http://www.slideshare.net/WushWu/predicting-winning-price-in-real-time-bidding-with-censored-data
