### ISSUE TITLE
lambda2 is missing in gradient of censored_regression2

### ISSUE THREAD

**Issue by ysk24ok** [wush978/KDD2015wpp#11]
https://github.com/wush978/KDD2015wpp/blob/master/WinningPrice.R#L77

It seems `lambda2` is missing on regularization term
in gradient calculation of censored_regression2 function.

May I send a PR for this?
If the objective of this repository is the **reproduction** of the experiment on the paper
and the implementation correctness doesn't matter, I will not.

**Comment by wush978** [comment]
Thanks for your reply.
I prefer directly fix it and cite this issue.
