### ISSUE TITLE
Difference in pdf, cdf formulas (paper vs code)

### ISSUE THREAD

**Issue by paliwal90** [wush978/KDD2015wpp#14]
https://github.com/wush978/KDD2015wpp/blob/master/WinningPrice.R#L67 
Here your z = (coefficients.dot(features) - true_vale) / sigma

But in paper http://www0.cs.ucl.ac.uk/staff/w.zhang/rtb-papers/win-price-pred.pdf 3.2 equation 5, it is z = (true_vale - coefficients.dot(features) ) / sigma

Why it's different?

**Comment by wush978** [comment]
Sorry, there is a mistake in our Eq.(5).

The Eq.(5) uses the winning probability, however, the $L$ is the losing bids. Therefore, it should be the losing probability.
