### ISSUE TITLE
Install IPinYouExp on Windows 7

### ISSUE THREAD

**Issue by mathycee** [wush978/KDD2015wpp#15]
Hi, I'm trying to run your code on Windows 7, however I'm having trouble installing the IPinYouExp. 
I downloaded the IPinYouExp folder and zipped it. Then run 
install.packages("C:/Users/.../IPinYouExp.zip", repos = NULL, type = "win.binary", lib="C:/.../R/R-3.3.3/library"), it seems to be installed successfully but when I load it it says ‘IPinYouExp’ is not a valid installed package.
What is the right way of installing this package on Windows 7? Thanks!

**Comment by wush978** [comment]
Sorry that I cannot help you.
It will take too much time for me to try the code on Windows.
Please use the same environment as I listed or find out by your self.
