### ISSUE TITLE
How it works online or on spark?

### ISSUE THREAD

**Issue by snakecy** [wush978/KDD2015wpp#2]
Thanks, on more questions, I wonder if the code could work online or on spark environment?

**Comment by wush978** [comment]
No, it could not. This is an offline experiment.

Now I am using the R package [pbdMPI](https://cran.r-project.org/web/packages/pbdMPI/index.html) to parallelize the optimization algorithm for online usage. For spark, I only use it to prepare the data. I do not know the optimization algorithm well used by spark, so I cannot give you any comment further.

**Comment by snakecy** [comment]
Thanks for your reply, I'm planing to use the sparkR in spark (1.5.1 version) to train offline data, then to test the predict online data. But It can't be parallelized and the model can't be saved on hdfs. And the training time is so long. So I'm confused.  
As you said, did your algorithm training part use only in local, but how you use the model online?
further more, can the three model use their own package in the experiment?

**Comment by wush978** [comment]
Yes, because all my experiences in the paper were conducted in a local machine. I did not implement the algorithm for spark or sparkR. 

In my opinion, the stochastic logistic regression should digest billions of data in a reasonable time period on single machine.

By the way, all the experiments of the paper is offline. Our online code contains too many optimization for our system, so I will not (and probably cannot) make these code public.

**Comment by snakecy** [comment]
Thanks,
btw, how much times will be spend on predicting station?

2015-10-25 12:45 GMT+08:00 Wush Wu notifications@github.com:

**Comment by snakecy** [comment]
If the censored regression model is exsit in R package?

2015-11-02 11:38 GMT+08:00 Snake Chow snakecker@gmail.com:

**Comment by wush978** [comment]
I am working on #3 recently and you can check the time by your self after I solving that issues.

You can find the implementation of censored regression in some packages of survival analysis but I cannot guarantee that they can run on the iPinYou dataset. Please check the function in https://github.com/wush978/KDD2015wpp/blob/master/WinningPrice.R#L65 for detailed implementation of your experiments.
