### ISSUE TITLE
Segfault Error when running example

### ISSUE THREAD

**Issue by mpearmain** [wush978/KDD2015wpp#3]
**\* caught segfault ***
address 0x7f552477e348, cause 'memory not mapped'

Traceback:
 1: .Call("IPinYouExp_OnlineSimulation", PACKAGE = "IPinYouExp",     Rm, Rlearner_ctr, Rlearner_wr, is_click, is_win, bid_t, clk_t,     is_continue)
 2: OnlineSimulation(m, learner_ctr, learner_wr, bidimpclk$is_click,     bidimpclk$is_win, bidimpclk$bid_t, bidimpclk$clk_t, i !=         1)
aborting ...
make: **\* [.fig9] Error 139

**Comment by wush978** [comment]
@mpearmain 
Does 684f8c8cc9e58ddd4219776b684fff7f3ba6e23b fix your issue?

**Comment by mpearmain** [comment]
Hi,

Im afraid not, ive the current master branch.
Only looks to fail on

docker run --rm -v
/home/mpearmain/gitpackages/KDD2015wpp:/var/local/KDD2015wpp
wush978/kdd2015wpp Rscript PredictCTR_WR_Fig9.R && docker run --rm -v
/home/mpearmain/gitpackages/KDD2015wpp:/var/local/KDD2015wpp
wush978/kdd2015wpp Rscript WinningPrice_Fig9.R | tee
log/WinningPrice_Fig9.log && touch .fig9

**Comment by wush978** [comment]
Dear @mpearmain ,

I think this is an environment dependent issue. I'll re-run this image again tonight. Could you provide me the following information?
- Are you using the docker image or your own R environment?
- Could you print the result of `sessionInfo()` after loading all required libraries? I need to identify the version of the packages you are using.

Thanks.

**Comment by mpearmain** [comment]
Hi im using the Docker image

Sending build context to Docker daemon 299.5 kB
Step 0 : FROM rocker/r-base
 ---> d8bc80a8b433
Step 1 : MAINTAINER Wush Wu wush978@gmail.com
 ---> Using cache
 ---> 5fe10a9ba78e
Step 2 : RUN apt-get update
 ---> Using cache
 ---> a4c5da980447
Step 3 : RUN echo "options(repos=c(cran='http://cran.rstudio.com/'))" >
/root/.Rprofile
 ---> Using cache
 ---> 3fb259c144f3
Step 4 : RUN Rscript -e "install.packages('dplyr')" &&   Rscript -e
"install.packages('data.table')"
 ---> Using cache
 ---> ffb1e7d4e1bf
Step 5 : RUN apt-get update
 ---> Using cache
 ---> 34aba04b6334
Step 6 : RUN apt-get install -y --no-install-recommends libxml2-dev
libcurl4-nss-dev libssl-dev ca-certificates git &&   Rscript -e
"install.packages(c('roxygen2', 'glmnet', 'FeatureHashing'))" &&   cd /root
&& git clone https://github.com/wush978/FastROC &&   R CMD INSTALL FastROC
 ---> Using cache
 ---> d95afa84423d
Step 7 : RUN Rscript -e "install.packages('knitr')" &&   Rscript -e
"install.packages('rmarkdown')"
 ---> Using cache
 ---> df3a0506b178
Step 8 : COPY IPinYouExp /root/IPinYouExp
 ---> Using cache
 ---> a815f3abe94e
Step 9 : RUN cd /root && R CMD INSTALL IPinYouExp
 ---> Using cache
 ---> b89ea9b9bb9b
Step 10 : VOLUME /var/local/KDD2015wpp
 ---> Using cache
 ---> 617a223d2c13
Step 11 : WORKDIR /var/local/KDD2015wpp
 ---> Using cache
 ---> 8bdda399fdfa
Successfully built 8bdda399fdfa

And session info:

> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_SG.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_SG.UTF-8        LC_COLLATE=en_SG.UTF-8
 [5] LC_MONETARY=en_SG.UTF-8    LC_MESSAGES=en_SG.UTF-8
 [7] LC_PAPER=en_SG.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_SG.UTF-8 LC_IDENTIFICATION=C

**Comment by mpearmain** [comment]
as an aisde Looking at the make file in line 5 you have:
all : .predict_wp .fig9 .winningpricectr
line 37 .winningprice_ctr

**Comment by wush978** [comment]
@mpearmain, thanks for your report.

I can reproduce this bug on my machine now. The valgrind reports two illegal read of memory and I need sometimes to figure it out...

**Comment by wush978** [comment]
Just an update:

I failed to create a minimal reproducible example of this issue (It failed if I directly `make` the project but the valgrind did not capture any memory error if I execute the script. That's strange!). I'll try to build the minimal example next weekend.

**Comment by wush978** [comment]
Hi @mpearmain,

Sorry for the late fix. Could you help me check if #4 fix your issue?

Thanks.

**Comment by jacky168** [comment]
I have encountered similar problem, the error message is presented below.

(2016-08-30 14:22:07) processing 2013-10-24...

 FALSE   TRUE   <NA>
238686    348   6863
online_simulation.cpp 87

 **\* caught segfault ***
address 0x7f221e4180b0, cause 'memory not mapped'

Traceback:
 1: .Call("IPinYouExp_OnlineSimulation", PACKAGE = "IPinYouExp",     Rm, Rlearner_ctr, Rlearner_wr, is_click, is_win, bid_t, clk_t,     is_continue)
 2: OnlineSimulation(m, learner_ctr, learner_wr, bidimpclk$is_click,     bidimpclk$is_win, bidimpclk$bid_t, bidimpclk$clk_t, i !=         1)
An irrecoverable exception occurred. R is aborting now ...
Makefile:35: recipe for target '.fig9' failed
make: **\* [.fig9] Error 139
