### ISSUE TITLE
Can't connect to the docker daemon error

### ISSUE THREAD

**Issue by LogyMero** [wush978/KDD2015wpp#5]
when I execute make it stopped while extracting the dataset zip ,the error written is 
docker run --rm -v /var/local/KDD2015wpp:/var/local/KDD2015wpp wush978/kdd2015wpp find ipinyou.contest.dataset/training2nd -name "_.bz2" -exec bunzip2 -f {} \;
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
make: *_\* [.decompress] Error 125

![screenshot from 2016-03-18 22-13-22](https://cloud.githubusercontent.com/assets/17952436/13900317/1319eaf2-ee0c-11e5-86eb-60027fb077a0.png)

**Comment by wush978** [comment]
You need to install docker properly. Please check this link: https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by LogyMero** [comment]
![12953117_1211089332264387_1611810440_o](https://cloud.githubusercontent.com/assets/17952436/14763588/fc4564c4-0999-11e6-9857-e2fd3783a708.png)

May you help me,Please? . why It is stopped at this point and don't move?
What can I do??

**Comment by wush978** [comment]
Try to monitor your CPU / memory usage.
