### ISSUE TITLE
Not able to install package in to R.

### ISSUE THREAD

**Issue by sahil1421011** [wush978/KDD2015wpp#7]
Hey,

I try to install this package in to R but it gives error

"`> devtools::install_github('wush978/KDD2015wpp/KDD2015wpp')`

> Downloading GitHub repo wush978/KDD2015wpp@master
> from URL https://api.github.com/repos/wush978/KDD2015wpp/zipball/master
> Error: Does not appear to be an R package (no DESCRIPTION)

"

**Comment by wush978** [comment]
Please check the `Makefile` for details of reproducing the experiments.
